name: CI — Prompt & Docs Sync

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install core deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyyaml jsonschema
          pip install ruff || true  # optional

      - name: Lint/Format (optional)
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check .
            ruff format --check . || true
          else
            echo "ruff not installed; skipping."
          fi

      - name: Validate prompt YAMLs against schema
        run: |
          if [ -f prompt_schema_min.json ]; then
            python tools/validate_prompts.py --schema prompt_schema_min.json
          else
            echo "prompt_schema_min.json not found; skipping schema validation."
          fi

      - name: Run eval harness (if present)
        run: |
          if [ -f eval_harness.py ]; then
            python eval_harness.py
          else
            echo "eval_harness.py not found; skipping."
          fi

      - name: Sync docs (if present)
        run: |
          if [ -f sync_orchestrator.py ] && [ -f doc_manifest.yaml ]; then
            python sync_orchestrator.py --manifest doc_manifest.yaml
            git diff --quiet || (echo "::error::Doc sync left changes; commit or fix." && exit 1)
          else
            echo "sync_orchestrator.py or doc_manifest.yaml missing; skipping."
          fi

      - name: Build SRS (if present)
        run: |
          if [ -f project_sync_orchestrator.py ] && [ -f SRS_template.md ]; then
            python project_sync_orchestrator.py --template SRS_template.md --out SRS.md
          else
            echo "SRS pipeline inputs missing; skipping."
          fi
