repos:
  - repo: local
    hooks:
      - id: spec-validate
        name: SPEC schema & examples validation
        entry: python SPEC/tools/validate_spec.py
        language: system
        pass_filenames: false
      - id: yamllint
        name: YAML lint (SPEC)
        entry: yamllint SPEC
        language: system
        pass_filenames: false
