repos:
  - repo: local
    hooks:
      - id: project-sync
        name: Project Sync (Prompts + Docs)
        entry: python project_sync_orchestrator.py
        language: system
        pass_filenames: false
